Implement union method in Sack class
aidubtech/mezages pull request #44
Opened 2024-01-26 03:40 UTC by belloibrahv

## Summary

This PR introduces the `union` method in the Sack class. The `union` method allows the merging of stores, with the option to specify a mount path. It addresses the need for combining and organizing different message stores within a Sack instance.

## Changes

- Added `union` method in Sack class
- Improved store validation and path adjustment
- Enhanced merging of buckets
- Wrote test for both `test_union_with_empty_store` & `test_union_without_mount_point` case.

## Benefits

- Provides a convenient way to merge stores within a Sack instance
- Improves code organization and readability
- Enables better handling of diverse message stores

2024-01-26 07:13 UTC, abdulfataiaka commented on src/mezages/sack.py
> +    def union(self, store: dict[str, set[str]], mount_path: Optional[str] = None) -> None:
`store: dict[str, InputMessages]` not `store: dict[str, set[str]]`, because we want the user to be able to provide bucket as either a set, list or tuple

Lets defined the the `InputMessages` after the `OutputMessages` in the bucket class as below

```python

InputMessages = Messages | OutputMessages | tuple[str, ...]

```

2024-01-26 07:17 UTC, abdulfataiaka commented on src/mezages/sack.py
> +        # validate arguments
Remove comment, code is clear

2024-01-26 07:17 UTC, abdulfataiaka commented on src/mezages/sack.py
> +        Store.ensure(store)
Space after line

2024-01-26 07:18 UTC, abdulfataiaka commented on src/mezages/sack.py
> +        if mount_path is not None:
Change to

```python

if mount_path: Path.ensure(mount_path)

```

2024-01-26 07:20 UTC, abdulfataiaka commented on src/mezages/sack.py
> +            Path(f'{mount_path}.{path}') if mount_path else Path(path): Bucket(bucket)
Change this to

```python

Path(f'{mount_path}.{path}' if mount_path else path): Bucket(bucket)

```

2024-01-26 07:25 UTC, abdulfataiaka commented on src/mezages/sack.py
> +                self.__store[path] = bucket
Oh! Ok. The above path joining can be moved into this block

```python

for path, bucket in store.items():
     new_path = Path(f'{mount_path}.{path}' if mount_path else path)

      if new_path in self.__store:
          self.__store[new_path].union(Bucket(bucket))
      else:
           self.__store[new_path] = Bucket(bucket)

```

2024-01-26 07:28 UTC, abdulfataiaka commented on src/mezages/sack.py
> +                self.__store[path] = bucket
You can rewrite the codes above to not perform unnecessary validations, since `Bucket(bucket)` calls `Bucket.ensure` internally. This has already been done when you did `Store.ensure` above

2024-01-26 07:37 UTC, abdulfataiaka requested changes
Left some comments

2024-01-26 07:46 UTC, abdulfataiaka commented
@belloibrahv You have more than just two scenarios to test, namely

When the input store provided is empty
When the input store provided is not empty but invalid

When the input store provided is not empty, it is valid, but the mount path is invalid

When the input store provided is not empty, it is valid, but the mount path is not provided or is None
When the input store provided is not empty, it is valid, but the mount path is a valid path

2024-01-26 08:07 UTC, belloibrahv commented on src/mezages/sack.py
> +    def union(self, store: dict[str, set[str]], mount_path: Optional[str] = None) -> None:
Ok, I will address the feedbacks as defined.

2024-01-26 17:01 UTC, belloibrahv commented
🤔 Hey @abdulfataiaka , I have a couple of questions regarding the tests for the union method:

*Invalid Store:*
* What would constitute an "invalid store" in our context?
*Invalid Path:*
* Similarly, what would be considered an "invalid path" when dealing with the union method?

you can provide some examples to illustrate what an invalid store and invalid path might look like.

2024-01-27 06:52 UTC, abdulfataiaka commented
I cannot see any of the comment addressed

2024-01-29 06:19 UTC, abdulfataiaka commented on src/mezages/sack.py
> +            if new_path in self.__state:
We can reduce lines 39 - 43 (4 lines) to the 2 lines below

```python

previous_bucket = self.__state.get(new_path, set())
self.__state[new_path] = previous_bucket.union(bucket)

```

2024-01-29 08:50 UTC, belloibrahv commented on src/mezages/sack.py
> +            if new_path in self.__state:
Ok cool

2024-01-29 11:03 UTC, merged