[ISSUES-10] Implement substitute subject for record types
aidubtech/mezages pull request #50
Opened 2024-01-30 12:38 UTC by belloibrahv

- Subject substitute now includes parent path for record types (e.g., "name in user" instead of "user.{name}").
- Updated tests to reflect new behavior.

2024-01-30 14:21 UTC, abdulfataiaka requested changes

2024-01-30 14:21 UTC, abdulfataiaka commented on src/mezages/subjects.py
> +
No need to comment on already clear code (Second time for this feedback)

Lines 75 to 78 can be compressed into

```python

return f'{key} in {parent_path}' if parent_path else key

```

2024-01-30 14:21 UTC, abdulfataiaka commented on src/mezages/subjects.py
> +
Lastly, note that key should not include the curly braces. As in `user` instead of `{user}`

2024-01-30 15:16 UTC, belloibrahv commented on src/mezages/subjects.py
> +
ok, resolved

2024-01-30 16:29 UTC, abdulfataiaka requested changes

2024-01-30 16:29 UTC, abdulfataiaka commented on src/mezages/subjects.py
> +
> Lastly, note that key should not include the curly braces. That is it should be `user` instead of `{user}`

You haven't addressed this comment

2024-01-30 16:29 UTC, abdulfataiaka commented on src/mezages/subjects.py
> +
Also, i don't really like that we are splitting the path two times. What do you think about the below instead

```python

if subject_parent_type == 'record':
      tokens = path.split('.') 
      parent_path = '.'.join(tokens[:-1])
      prop = tokens[-1].strip('{').strip('}')
      return f'{prop} in {parent_path}' if parent_path else prop

```

2024-01-30 23:18 UTC, abdulfataiaka approved these changes
LGTM

2024-02-01 09:09 UTC, yuusuf4real approved these changes

2024-02-01 09:19 UTC, merged